[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "amqtt"
version = "0.1.0"

[dependencies]
mqtt-protocol = "*"
time = "*"
rand = "*"

[dependencies.mioco]
git = "https://github.com/dpc/mioco.git"