[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.3.0"

[dependencies]
chan = "0.1"
log = "0.3"
mioco = "0.7"
rand = "0.3"
time = "0.1"

[dependencies.mqtt-protocol]
git = "https://github.com/kteza1/mqtt-rs.git"
branch = "patch-2"

[dependencies.openssl]
features = ["tlsv1_1", "tlsv1_2"]
optional = true
version = "0.7"

[dev-dependencies]
env_logger = "0.3"

[features]
default = ["ssl"]
ssl = ["openssl"]
