[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.1.0"

[dependencies]
mqtt-protocol = {git = "https://github.com/kteza1/mqtt-rs.git"}
time = "*"
rand = "*"
log = "*"
mioco = "*"

[dev-dependencies]
env_logger = "0.3"
