[package]
authors = ["tekjar <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.20.0"
description = "A fast, lockfree mqtt client"
repository = "https://github.com/AtherEnergy/rumqtt"
readme = "README.md"
license = "Unlicense/MIT"
keywords = ["mqtt", "iot", "async", "tokio", "futures"]

[dependencies]
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
bytes = "0.4"
mqtt3 = { git = "https://github.com/tekjar/mqtt3" }
quick-error = "1.2"
log = "0.3"
threadpool = "1"

[dev-dependencies]
loggerv = "0.3"
