[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.2.1"

[dependencies]
chan = "0.1"
log = "0.3"
mio = "*"
rand = "0.3"
time = "0.1"
mqtt-protocol = "0.1"

[dependencies.openssl]
features = ["tlsv1_1", "tlsv1_2"]
optional = true
version = "0.7"

[dev-dependencies]
env_logger = "0.3"

[features]
default = ["ssl"]
ssl = ["openssl"]
