[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.1.0"

[dependencies]
log = "*"
mio = "*"
mioco = "*"
rand = "*"
time = "*"

[dependencies.mqtt-protocol]
git = "https://github.com/kteza1/mqtt-rs.git"

[dev-dependencies]
env_logger = "0.3"
