[package]
name = "mqtt"
version = "0.1.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]

[lib]
name = "mqtt"

[dependencies]
byteorder = "^0.3.13"
log = "^0.3.2"
regex = "^0.1.41"

[dev-dependencies]
env_logger = "^0.3.1"
clap = "^1.4.0"
uuid = "^0.1.17"
