[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.4.0"
description = "A fast, lockfree mqtt client"
documentation = "http://ather-energy.github.io/RuMqtt/rumqtt/index.html"
repository = "https://github.com/Ather-Energy/RuMqtt"
readme = "README.md"
license = "Unlicense/MIT"
exclude = ["tests/test-utils"]
keywords = ["mqtt", "iot"]

[dependencies]
chan = "0.1"
log = "0.3"
mio = "0.5"
rand = "0.3"
time = "0.1"
mqtt-protocol = "0.1"

[dependencies.openssl]
features = ["tlsv1_1", "tlsv1_2"]
optional = true
version = "0.7"

[dev-dependencies]
env_logger = "0.3"

[features]
default = ["ssl"]
ssl = ["openssl"]
